"""modify applynew to apply

Revision ID: 28c53d12921c
Revises: c9b2b5ba89ba
Create Date: 2024-09-25 17:52:53.294147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c53d12921c'
down_revision: Union[str, None] = 'c9b2b5ba89ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('repo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('role', sa.VARCHAR(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('record_time', sa.DateTime(), nullable=True),
    sa.Column('apply_time', sa.DateTime(), nullable=True),
    sa.Column('apply_status', sa.Boolean(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('confirm_time', sa.DateTime(), nullable=True),
    sa.Column('coin_amount', sa.Float(), nullable=True),
    sa.Column('repo_owner_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('state', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('apply_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply_new',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('repo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('role', sa.VARCHAR(length=200), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('record_time', sa.DATETIME(), nullable=True),
    sa.Column('apply_time', sa.DATETIME(), nullable=True),
    sa.Column('apply_status', sa.BOOLEAN(), nullable=True),
    sa.Column('supervisor_id', sa.INTEGER(), nullable=True),
    sa.Column('decision', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('confirm_time', sa.DATETIME(), nullable=True),
    sa.Column('coin_amount', sa.FLOAT(), nullable=True),
    sa.Column('repo_owner_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pid', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('state', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('apply')
    # ### end Alembic commands ###
