"""coin database

Revision ID: 39f5ba1accaf
Revises: 6e68d1335698
Create Date: 2024-07-03 20:33:32.168215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39f5ba1accaf'
down_revision: Union[str, None] = '6e68d1335698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('audit_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'audit_id')
    op.drop_column('order', 'phone')
    # ### end Alembic commands ###
