"""coin database

Revision ID: 6e68d1335698
Revises: 754e889b4bf4
Create Date: 2024-06-12 16:43:51.356159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e68d1335698'
down_revision: Union[str, None] = '754e889b4bf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('describe', sa.VARCHAR(length=1500), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('prince', sa.Float(), nullable=True),
    sa.Column('create_user', sa.Integer(), nullable=True),
    sa.Column('img_path', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('itemid', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.VARCHAR(length=200), nullable=True),
    sa.Column('status', sa.VARCHAR(length=1), nullable=True),
    sa.Column('toal_price', sa.Float(), nullable=True),
    sa.Column('address', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('item')
    # ### end Alembic commands ###
