"""coin database

Revision ID: 754e889b4bf4
Revises: 
Create Date: 2024-06-02 16:57:57.905963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754e889b4bf4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('repo', sa.VARCHAR(length=200), nullable=True),
    sa.Column('role', sa.VARCHAR(length=200), nullable=True),
    sa.Column('content', sa.VARCHAR(length=500), nullable=True),
    sa.Column('record_time', sa.DateTime(), nullable=True),
    sa.Column('apply_time', sa.DateTime(), nullable=True),
    sa.Column('apply_status', sa.Boolean(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('confirm_time', sa.DateTime(), nullable=True),
    sa.Column('coin_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=200), nullable=True),
    sa.Column('content', sa.VARCHAR(length=200), nullable=True),
    sa.Column('change_amount', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consume',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.VARCHAR(length=200), nullable=True),
    sa.Column('apply_time', sa.DateTime(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('confirm_time', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('register',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=False),
    sa.Column('password', sa.VARCHAR(length=500), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=80), nullable=True),
    sa.Column('notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=False),
    sa.Column('github', sa.VARCHAR(length=200), nullable=True),
    sa.Column('password', sa.VARCHAR(length=500), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=80), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=32), nullable=True),
    sa.Column('location', sa.VARCHAR(length=32), nullable=True),
    sa.Column('role', sa.VARCHAR(length=32), nullable=True),
    sa.Column('coin', sa.Float(), nullable=True),
    sa.Column('avantar', sa.VARCHAR(length=256), nullable=True),
    sa.Column('desc', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('register')
    op.drop_table('consume')
    op.drop_table('bill')
    op.drop_table('apply')
    # ### end Alembic commands ###
