"""remove class apply column content nullable=true

Revision ID: fcbda19573e9
Revises: eee8a56ced60
Create Date: 2024-09-25 17:38:19.478702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbda19573e9'
down_revision: Union[str, None] = 'eee8a56ced60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
